name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  csprojFile:  # id of input
    description: 'project file'
    required: true
outputs:
  version: # id of output
    description: 'app version'
runs:
  using: 'node16'
  main: 'node --max-old-space-size=4096 dist/index.js'