name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  filename:  # id of input
    description: 'project file'
    required: true
  dotnetVersion:
    description: 'version of dotnet framework'
    required: true
  updType:
    description: 'major minor patch or build'
    required: true
outputs:
  version:
    description: 'new version'
runs:
  using: 'node12'
  main: 'dist/index.js'