name: Release
'on':
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: '${{ github.repository }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.package-version.outputs.current-version }}
          message: "Latest release"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}